---
 ### RDP and SMB features installation with when condition

- name: RDP installation
  win_feature:
    name: Remote-Desktop-Services
    included_sub_features: yes
    status: present
  when:  ansible_distribution == "Microsoft Windows Server 2019 Datacenter" 
  register: win_feature
  notify: reboot_server



- name: SMB 1.0 CIFS file share support 
  win_feature:
    name: FS-SMB1
    included_sub_features: yes
    status: present
  when: ansible_system_description == "This is the first file server"
  register: win_feature
  notify: reboot_server




...
